### ISSUE TITLE
npm WARN and ERR due to Incorrect @angular/form Dependency in @acrodata/gui@0.2.4

### ISSUE THREAD

**Issue by whwanyt** [acrodata/gui#1]
## Description
When attempting to install @acrodata/gui@0.2.4, npm encounters warnings and errors due to an incorrect peer dependency listed in `peerDependencies` as `@angular/form`. The correct dependency should be `@angular/forms`.

## Error Details
The following warnings and errors are generated during installation:

```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @acrodata/gui@0.2.4
npm WARN Found: @angular/form@undefined
npm WARN node_modules/@angular/form
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @angular/form@">=15.0.0" from @acrodata/gui@0.2.4
npm WARN node_modules/@acrodata/gui
npm WARN @acrodata/gui@"*" from the root project
npm ERR! Cannot read properties of null (reading 'matches')
```

This indicates that the `@angular/form` module cannot be correctly resolved, as it should actually depend on `@angular/forms`.

## Expected Behavior
The `peerDependencies` in the `package.json` should be corrected from `@angular/form` to `@angular/forms` to fix the dependency resolution issue during installation.

## Steps to Reproduce
1. Attempt to install @acrodata/gui@0.2.4
2. Observe the aforementioned npm warnings and errors

## Possible Solution
Please correct the dependency in the project's `package.json` file, changing `@angular/form` in `peerDependencies` to `@angular/forms`.

## Additional Information
```
node v20.9.0
npm v10.1.0
```

Thank you!

**Comment by nzbin** [comment]
Many thanks for your advice, `0.2.5` has fixed.

**Comment by whwanyt** [comment]
Thank you for the quick response and fix! I've reviewed the changes, and everything looks good to me. The issue I was experiencing has been resolved. I appreciate your hard work and prompt attention to this matter. I'll go ahead and close this issue now. Thanks again!
